name: pluto_grid_plus_export
description: PlutoGridExport converts PlutoGrid's metadata to CSV or PDF. Used with PlutoGrid.
version: 1.0.2
homepage: https://bosskmk.github.io
repository: https://github.com/bosskmk/pluto_grid/tree/master/packages/pluto_grid_plus_export

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  pluto_grid_plus: ^8.3.0
  csv: ^5.1.1
  pdf: ^3.10.7
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.3
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
