name: pluto_grid_plus_export
description: PlutoGridExport converts PlutoGrid's metadata to CSV or PDF. Used with PlutoGrid.
version: 1.0.5
homepage: https://bosskmk.github.io
repository: https://github.com/doonfrs/pluto_grid_plus/tree/master/packages/pluto_grid_plus_export

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  pluto_grid_plus: ^8.4.3
  csv: ^6.0.0
  pdf: ^3.10.7
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.3
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
