name: pluto_grid_export
description: PlutoGridExport converts PlutoGrid's metadata to CSV or PDF. Used with PlutoGrid.
version: 1.0.5
homepage: https://bosskmk.github.io
repository: https://github.com/bosskmk/pluto_grid/tree/master/packages/pluto_grid_export
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  pluto_grid:
    git:
      url: https://github.com/ujwalbasnet1/pluto_grid.git
      ref: 0c703a7bdf34117d1c9d9a0b3152e2cafb715fac
  csv: ^5.0.1
  pdf: ^3.10.3
  printing: ^5.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  build_runner: ^2.3.0
  flutter_lints: ^2.0.1
