name: pluto_grid
description: PlutoGrid is a dataGrid that can be controlled by the keyboard on desktop and web. Of course, it works well on Android and IOS. (DataGrid, DataTable, Data Grid, Data Table, Sticky)
version: 7.0.1
homepage: https://pluto.weblaze.dev
repository: https://github.com/bosskmk/pluto_grid

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  rxdart: ^0.27.7
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.2
  flutter_lints: ^2.0.1
