name: pluto_grid
description: PlutoGrid is a dataGrid that can be controlled by the keyboard on desktop and web. Of course, it works well on Android and IOS. (DataGrid, DataTable, Data Grid, Data Table, Sticky)
version: 3.0.1
homepage: https://bosskmk.github.io
repository: https://github.com/bosskmk/pluto_grid

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  rxdart: ^0.27.3
  linked_scroll_controller: ^0.2.0
  collection: ^1.15.0
  csv: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  build_runner: ^2.1.10
  flutter_lints: ^2.0.1
